import { readFileSync } from "node:fs";
import { Database } from "bun:sqlite";
import postgres from "postgres";

export type Sql = {
  <T extends Record<string, unknown>[] = Record<string, unknown>[]>(
    strings: TemplateStringsArray,
    ...values: unknown[]
  ): Promise<T>;
  unsafe<T extends Record<string, unknown>[] = Record<string, unknown>[]>(sql: string, values?: unknown[]): Promise<T>;
  begin<T>(callback: (sql: Sql) => Promise<T>): Promise<T>;
  exec(sql: string): Promise<void>;
  end(): Promise<void>;
  dialect: "sqlite" | "postgres";
};

function sqliteDb(path: string): Sql {
  const sqlite = new Database(path, { create: true, strict: true });
  sqlite.exec("PRAGMA foreign_keys = ON");

  const query = async <T extends Record<string, unknown>[]>(sql: string, values: unknown[] = []): Promise<T> =>
    sqlite.query(sql).all(...values) as T;
  const db = (async <T extends Record<string, unknown>[]>(strings: TemplateStringsArray, ...values: unknown[]) => {
    let sql = strings[0];
    for (let i = 0; i < values.length; i += 1) sql += `?${strings[i + 1]}`;
    return query<T>(sql, values);
  }) as Sql;
  db.unsafe = query;
  db.begin = async <T>(callback: (sql: Sql) => Promise<T>): Promise<T> => {
    sqlite.exec("BEGIN");
    try {
      const result = await callback(db);
      sqlite.exec("COMMIT");
      return result;
    } catch (error) {
      sqlite.exec("ROLLBACK");
      throw error;
    }
  };
  db.exec = async (sql: string) => { sqlite.exec(sql); };
  db.end = async () => { sqlite.close(); };
  db.dialect = "sqlite";
  return db;
}

function postgresDb(url: string): Sql {
  const pg = postgres(url);
  const wrap = (client: postgres.Sql, close: () => Promise<void>): Sql => {
    const db = (async <T extends Record<string, unknown>[]>(strings: TemplateStringsArray, ...values: unknown[]) =>
      client<T>(strings, ...values)) as Sql;
    db.unsafe = async <T extends Record<string, unknown>[]>(sql: string, values: unknown[] = []) => {
      let parameter = 0;
      const pgSql = sql.replaceAll("?", () => `$${++parameter}`);
      return client.unsafe<T>(pgSql, values);
    };
    db.begin = async <T>(callback: (sql: Sql) => Promise<T>) =>
      client.begin((transaction) => callback(wrap(transaction, async () => {})));
    db.exec = async (sql: string) => { await client.unsafe(sql); };
    db.end = close;
    db.dialect = "postgres";
    return db;
  };
  return wrap(pg, async () => { await pg.end(); });
}

export type Artist = {
  id: number;
  name: string;
};

export type LickAggregate = {
  id: number;
  artist_id: number;
  artist_name: string;
  lick_name: string;
  lick_url: string | null;
  goal_bpm: number;
  best_bpm: number | null;
  pct_of_goal: number | null;
  first_date: string | null;
  last_date: string | null;
  session_count: number;
  can_add_today: boolean;
};

export type Session = {
  id: number;
  lick_id: number;
  date: string;
  bpm: number;
};

export type StatsDay = {
  date: string;
  session_count: number;
};

export type StatsSessionBarsDay = {
  date: string;
  first_sessions: number;
  completion_sessions: number;
  progression_sessions: number;
  first_completion_sessions: number;
};

export type StatsProgressBarsDay = {
  date: string;
  progress_values: number[];
};

export type StatsBpmBarsDay = {
  date: string;
  first_sessions: number;
  delta_bins: Array<{
    delta_bin: number;
    session_count: number;
  }>;
};

export type StatsBars = {
  sessions: StatsSessionBarsDay[];
  progress: StatsProgressBarsDay[];
  bpm_deltas: StatsBpmBarsDay[];
};

export type StatsHistogramBin = {
  bucket: number;
  count: number;
};

export type StatsHistograms = {
  session_deltas: StatsHistogramBin[];
  sessions_to_complete: StatsHistogramBin[];
  days_to_complete: StatsHistogramBin[];
};

export type StatsProgressBin = {
  bucket_pct: number;
  lick_count: number;
};

export type SessionBpmRange = {
  min: number;
  max: number;
};

export type CreateLickInput = {
  lickName: string;
  goalBpm: number;
  lickUrl?: string;
};

const SORT_MAP: Record<string, string> = {
  artist: "artist_name",
  lick: "lick_name",
  goal: "goal_bpm",
  best: "best_bpm",
  pct: "pct_of_goal",
  sessions: "session_count",
  first: "first_date",
  last: "last_date",
};

const SESSION_SORT_MAP: Record<string, string> = {
  date: "date",
  bpm: "bpm",
};

export function openDb(location: string): Sql {
  return location.startsWith("postgres://") || location.startsWith("postgresql://")
    ? postgresDb(location)
    : sqliteDb(location.replace(/^sqlite:/, ""));
}

export async function initSchema(db: Sql): Promise<void> {
  const schemaPath = new URL("./schema.sql", import.meta.url);
  let sql = readFileSync(schemaPath, "utf8");
  if (db.dialect === "postgres") {
    sql = sql.replaceAll("id INTEGER PRIMARY KEY", "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
  }
  await db.exec(sql);
}

export async function getArtists(db: Sql): Promise<Artist[]> {
  const rows = await db<Artist[]>`SELECT id, name FROM artists ORDER BY name ASC`;
  return rows.map(r => ({
    id: Number(r.id),
    name: String(r.name)
  }));
}

export async function createArtist(db: Sql, artistName: string): Promise<number> {
  const cleanArtist = artistName.trim();
  if (!cleanArtist) {
    throw new Error("artistName is required");
  }

  const rows = await db<{ id: number }[]>`INSERT INTO artists(name) VALUES (${cleanArtist}) RETURNING id`;
  if (rows.length === 0) {
    throw new Error("Failed to create artist");
  }
  return Number(rows[0].id);
}

export async function updateArtist(db: Sql, artistId: number, artistName: string): Promise<void> {
  if (!Number.isInteger(artistId) || artistId <= 0) {
    throw new Error("artistId must be a positive integer");
  }
  const cleanArtist = artistName.trim();
  if (!cleanArtist) {
    throw new Error("artistName is required");
  }

  const existing = await db`SELECT id FROM artists WHERE id = ${artistId}`;
  if (existing.length === 0) {
    throw new Error("Artist not found");
  }

  await db`UPDATE artists SET name = ${cleanArtist} WHERE id = ${artistId}`;
}

export async function createLick(
  db: Sql,
  artistName: string,
  lickName: string,
  goalBpm: number,
  lickUrl?: string,
): Promise<number> {
  const ids = await createLicks(db, artistName, [{ lickName, goalBpm, lickUrl }]);
  return ids[0];
}

export async function createLicks(
  db: Sql,
  artistName: string,
  licks: CreateLickInput[],
): Promise<number[]> {
  const cleanArtist = artistName.trim();
  if (!cleanArtist) {
    throw new Error("artistName is required");
  }
  if (!Array.isArray(licks) || licks.length === 0) {
    throw new Error("At least one lick is required");
  }

  const prepared = licks.map(({ lickName, goalBpm, lickUrl }) => {
    const cleanLick = lickName.trim();
    if (!cleanLick) {
      throw new Error("lickName is required");
    }
    if (!Number.isInteger(goalBpm) || goalBpm <= 0) {
      throw new Error("goalBpm must be a positive integer");
    }
    return {
      lickName: cleanLick,
      goalBpm,
      lickUrl: lickUrl?.trim() ? lickUrl.trim() : null,
    };
  });

  const createdIds: number[] = [];

  await db.begin(async (sql) => {
    await sql`INSERT INTO artists(name) VALUES (${cleanArtist}) ON CONFLICT (name) DO NOTHING`;
    const row = await sql<{ id: number }[]>`SELECT id FROM artists WHERE name = ${cleanArtist}`;
    if (row.length === 0) {
      throw new Error("Failed to resolve artist");
    }
    const artistId = Number(row[0].id);

    for (const lick of prepared) {
      const created = await sql<{ id: number }[]>`
        INSERT INTO licks(artist_id, name, url, goal_bpm)
        VALUES (${artistId}, ${lick.lickName}, ${lick.lickUrl}, ${lick.goalBpm})
        RETURNING id
      `;
      if (created.length === 0) {
        throw new Error("Failed to create lick");
      }
      createdIds.push(Number(created[0].id));
    }
  });

  return createdIds;
}

export async function updateLick(
  db: Sql,
  lickId: number,
  lickName: string,
  goalBpm: number,
  lickUrl?: string,
): Promise<void> {
  if (!Number.isInteger(lickId) || lickId <= 0) {
    throw new Error("lickId must be a positive integer");
  }
  const cleanLick = lickName.trim();
  if (!cleanLick) {
    throw new Error("lickName is required");
  }
  if (!Number.isInteger(goalBpm) || goalBpm <= 0) {
    throw new Error("goalBpm must be a positive integer");
  }

  const rows = await db<{ id: number; best_bpm: string | number | null }[]>`
    SELECT
      l.id,
      MAX(s.bpm) AS best_bpm
    FROM licks l
    LEFT JOIN sessions s ON s.lick_id = l.id
    WHERE l.id = ${lickId}
    GROUP BY l.id
  `;
  if (rows.length === 0) {
    throw new Error("Lick not found");
  }
  const meta = rows[0];
  const bestBpm = meta.best_bpm === null ? null : Number(meta.best_bpm);

  const minGoal = bestBpm === null ? 1 : bestBpm;
  if (goalBpm < minGoal) {
    throw new Error(`goalBpm must be at least ${minGoal}`);
  }

  const cleanUrl = lickUrl?.trim() ? lickUrl.trim() : null;
  await db`UPDATE licks SET name = ${cleanLick}, url = ${cleanUrl}, goal_bpm = ${goalBpm} WHERE id = ${lickId}`;
}

export async function getLicks(
  db: Sql,
  artistId: number | null,
  sortBy: string,
  sortDir: string,
  localDate: string,
): Promise<LickAggregate[]> {
  const sortColumn = SORT_MAP[sortBy] ?? "artist_name";
  const sortDirection = sortDir?.toLowerCase() === "desc" ? "DESC" : "ASC";

  const base = `
    SELECT
      l.id,
      a.id AS artist_id,
      a.name AS artist_name,
      l.name AS lick_name,
      l.url AS lick_url,
      l.goal_bpm,
      MAX(s.bpm) AS best_bpm,
      CASE
        WHEN MAX(s.bpm) IS NULL THEN NULL
        ELSE CAST(ROUND((MAX(s.bpm) * 100.0) / l.goal_bpm) AS INTEGER)
      END AS pct_of_goal,
      MIN(s.date) AS first_date,
      MAX(s.date) AS last_date,
      COUNT(s.id) AS session_count,
      CASE
        WHEN MAX(s.bpm) >= l.goal_bpm THEN 0
        ELSE 1
      END AS can_add_today
    FROM licks l
    JOIN artists a ON a.id = l.artist_id
    LEFT JOIN sessions s ON s.lick_id = l.id
    %ARTIST_FILTER%
    GROUP BY l.id, a.id, a.name, l.name, l.url, l.goal_bpm
    ORDER BY ${sortColumn} ${sortDirection}, l.id ASC
  `;

  let rows;
  if (artistId === null) {
    const sql = base.replace("%ARTIST_FILTER%", "");
    rows = await db.unsafe(sql);
  } else {
    const sql = base.replace("%ARTIST_FILTER%", "WHERE a.id = ?");
    rows = await db.unsafe(sql, [artistId]);
  }

  return rows.map((r: any) => ({
    id: Number(r.id),
    artist_id: Number(r.artist_id),
    artist_name: String(r.artist_name),
    lick_name: String(r.lick_name),
    lick_url: r.lick_url ? String(r.lick_url) : null,
    goal_bpm: Number(r.goal_bpm),
    best_bpm: r.best_bpm === null ? null : Number(r.best_bpm),
    pct_of_goal: r.pct_of_goal === null ? null : Number(r.pct_of_goal),
    first_date: r.first_date ? String(r.first_date) : null,
    last_date: r.last_date ? String(r.last_date) : null,
    session_count: Number(r.session_count),
    can_add_today: Boolean(r.can_add_today),
  })) as LickAggregate[];
}

export async function getLickMeta(
  db: Sql,
  lickId: number,
): Promise<{ goal_bpm: number; best_bpm: number | null } | null> {
  const rows = await db<{ goal_bpm: number; best_bpm: string | number | null }[]>`
    SELECT
      l.goal_bpm,
      MAX(s.bpm) AS best_bpm
    FROM licks l
    LEFT JOIN sessions s ON s.lick_id = l.id
    WHERE l.id = ${lickId}
    GROUP BY l.id, l.goal_bpm
  `;
  if (rows.length === 0) {
    return null;
  }
  return {
    goal_bpm: Number(rows[0].goal_bpm),
    best_bpm: rows[0].best_bpm === null ? null : Number(rows[0].best_bpm),
  };
}

export async function hasSessionForDate(
  db: Sql,
  lickId: number,
  date: string,
): Promise<boolean> {
  const rows = await db`SELECT 1 AS found FROM sessions WHERE lick_id = ${lickId} AND date = ${date}`;
  return rows.length > 0;
}

export async function addSession(
  db: Sql,
  lickId: number,
  date: string,
  bpm: number,
): Promise<number> {
  if (!Number.isInteger(bpm) || bpm <= 0) {
    throw new Error("bpm must be a positive integer");
  }

  const rows = await db<{ id: number }[]>`
    INSERT INTO sessions(lick_id, date, bpm)
    VALUES (${lickId}, ${date}, ${bpm})
    ON CONFLICT(lick_id, date) DO UPDATE SET bpm = EXCLUDED.bpm
    RETURNING id
  `;
  if (rows.length === 0) {
    throw new Error("Failed to create session");
  }
  return Number(rows[0].id);
}

export function getSessionBpmRange(
  bestBpm: number | null,
  goalBpm: number,
): SessionBpmRange {
  if (!Number.isInteger(goalBpm) || goalBpm <= 0) {
    throw new Error("goalBpm must be a positive integer");
  }
  const min = bestBpm === null ? 1 : Math.min(bestBpm + 1, goalBpm);
  return { min, max: goalBpm };
}

export async function getSessions(
  db: Sql,
  lickId: number,
  sortBy: string,
  sortDir: string,
): Promise<Session[]> {
  const sortColumn = SESSION_SORT_MAP[sortBy] ?? "date";
  const sortDirection = sortDir?.toLowerCase() === "desc" ? "DESC" : "ASC";
  
  const query = `
    SELECT id, lick_id, date, bpm
    FROM sessions
    WHERE lick_id = ?
    ORDER BY ${sortColumn} ${sortDirection}, id ASC
  `;

  const rows = await db.unsafe(query, [lickId]);
  return rows.map((r: any) => ({
    id: Number(r.id),
    lick_id: Number(r.lick_id),
    date: String(r.date),
    bpm: Number(r.bpm),
  }));
}

export async function getStats(db: Sql): Promise<StatsDay[]> {
  const rows = await db`
    SELECT
      date,
      COUNT(*) AS session_count
    FROM sessions
    GROUP BY date
    ORDER BY date ASC
  `;
  return rows.map((r: any) => ({
    date: String(r.date),
    session_count: Number(r.session_count),
  }));
}

type SessionRow = {
  id: number;
  lick_id: number;
  date: string;
  bpm: number;
  goal_bpm: number;
};

async function querySessionRows(db: Sql): Promise<SessionRow[]> {
  const rows = await db`
    SELECT
      s.id,
      s.lick_id,
      s.date,
      s.bpm,
      l.goal_bpm
    FROM sessions s
    JOIN licks l ON l.id = s.lick_id
    ORDER BY s.lick_id ASC, s.date ASC, s.id ASC
  `;
  return rows.map((r: any) => ({
    id: Number(r.id),
    lick_id: Number(r.lick_id),
    date: String(r.date),
    bpm: Number(r.bpm),
    goal_bpm: Number(r.goal_bpm),
  }));
}

export async function getStatsBars(db: Sql): Promise<StatsBars> {
  const rows = await querySessionRows(db);

  const sessionsByDate = new Map<string, StatsSessionBarsDay>();
  const progressByDate = new Map<string, number[]>();
  const bpmDeltasByDate = new Map<string, { first_sessions: number; delta_bins: Map<number, number> }>();
  const lickState = new Map<number, {
    seen: boolean;
    prev_pct: number | null;
    prev_bpm: number | null;
    reached_goal: boolean;
  }>();

  for (const row of rows) {
    const pct = (row.bpm * 100) / row.goal_bpm;
    let day = sessionsByDate.get(row.date);
    if (!day) {
      day = {
        date: row.date,
        first_sessions: 0,
        completion_sessions: 0,
        progression_sessions: 0,
        first_completion_sessions: 0,
      };
      sessionsByDate.set(row.date, day);
    }

    const state = lickState.get(row.lick_id) ?? {
      seen: false,
      prev_pct: null,
      prev_bpm: null,
      reached_goal: false,
    };
    let bpmDay = bpmDeltasByDate.get(row.date);
    if (!bpmDay) {
      bpmDay = { first_sessions: 0, delta_bins: new Map<number, number>() };
      bpmDeltasByDate.set(row.date, bpmDay);
    }

    if (!state.seen && pct >= 100) {
      day.first_completion_sessions += 1;
      bpmDay.first_sessions += 1;
    } else if (!state.seen) {
      day.first_sessions += 1;
      bpmDay.first_sessions += 1;
    } else if (!state.reached_goal && pct >= 100) {
      day.completion_sessions += 1;
    } else {
      day.progression_sessions += 1;
    }

    const delta = state.prev_pct === null ? 10 : pct - state.prev_pct;
    if (state.prev_bpm !== null) {
      const bpmDelta = Math.abs(row.bpm - state.prev_bpm);
      const deltaBin = Math.max(5, Math.ceil(Math.max(bpmDelta, 0.1) / 5) * 5);
      bpmDay.delta_bins.set(deltaBin, (bpmDay.delta_bins.get(deltaBin) ?? 0) + 1);
    }
    const roundedDelta = Math.round(delta * 10) / 10;
    const progressParts = progressByDate.get(row.date) ?? [];
    progressParts.push(roundedDelta);
    progressByDate.set(row.date, progressParts);

    state.seen = true;
    state.prev_pct = pct;
    state.prev_bpm = row.bpm;
    if (pct >= 100) {
      state.reached_goal = true;
    }
    lickState.set(row.lick_id, state);
  }

  const dates = [...sessionsByDate.keys()].sort();
  return {
    sessions: dates.map((date) => sessionsByDate.get(date)!),
    progress: dates.map((date) => ({
      date,
      progress_values: progressByDate.get(date) ?? [],
    })),
    bpm_deltas: dates.map((date) => {
      const row = bpmDeltasByDate.get(date) ?? { first_sessions: 0, delta_bins: new Map<number, number>() };
      const delta_bins = [...row.delta_bins.entries()]
        .sort((a, b) => a[0] - b[0])
        .map(([delta_bin, session_count]) => ({ delta_bin, session_count }));
      return {
        date,
        first_sessions: row.first_sessions,
        delta_bins,
      };
    }),
  };
}

export async function getProgressDistribution(db: Sql): Promise<StatsProgressBin[]> {
  const rows = await db<{ id: number; goal_bpm: number; best_bpm: string | number | null }[]>`
    SELECT
      l.id,
      l.goal_bpm,
      MAX(s.bpm) AS best_bpm
    FROM licks l
    LEFT JOIN sessions s ON s.lick_id = l.id
    GROUP BY l.id, l.goal_bpm
  `;

  const counts = new Map<number, number>();
  for (let bucket = 0; bucket <= 100; bucket += 10) {
    counts.set(bucket, 0);
  }

  for (const row of rows) {
    const bestBpm = row.best_bpm === null ? null : Number(row.best_bpm);
    const pct = bestBpm === null ? 0 : (bestBpm * 100) / Number(row.goal_bpm);
    const bucket = pct >= 100 ? 100 : Math.floor(Math.max(0, pct) / 10) * 10;
    counts.set(bucket, (counts.get(bucket) ?? 0) + 1);
  }

  const output: StatsProgressBin[] = [];
  for (let bucket = 0; bucket <= 100; bucket += 10) {
    output.push({
      bucket_pct: bucket,
      lick_count: counts.get(bucket) ?? 0,
    });
  }
  return output;
}

function incrementBucket(map: Map<number, number>, bucket: number): void {
  map.set(bucket, (map.get(bucket) ?? 0) + 1);
}

function toSortedBins(map: Map<number, number>): StatsHistogramBin[] {
  return [...map.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([bucket, count]) => ({ bucket, count }));
}

function diffDaysUtc(start: string, end: string): number {
  const startMs = Date.parse(`${start}T00:00:00Z`);
  const endMs = Date.parse(`${end}T00:00:00Z`);
  if (!Number.isFinite(startMs) || !Number.isFinite(endMs)) {
    return 0;
  }
  return Math.floor((endMs - startMs) / 86400000);
}

export async function getStatsHistograms(db: Sql): Promise<StatsHistograms> {
  const rows = await querySessionRows(db);

  const deltaCounts = new Map<number, number>();
  const sessionsToCompleteCounts = new Map<number, number>();
  const daysToCompleteCounts = new Map<number, number>();
  const lickState = new Map<number, {
    goal_bpm: number;
    prev_bpm: number | null;
    first_date: string | null;
    session_count: number;
    completed: boolean;
  }>();

  for (const row of rows) {
    const state = lickState.get(row.lick_id) ?? {
      goal_bpm: row.goal_bpm,
      prev_bpm: null,
      first_date: null,
      session_count: 0,
      completed: false,
    };
    state.session_count += 1;
    if (state.first_date === null) {
      state.first_date = row.date;
    }

    if (state.prev_bpm !== null) {
      const delta = Math.abs(row.bpm - state.prev_bpm);
      const bucket = Math.max(5, Math.ceil(Math.max(delta, 1) / 5) * 5);
      incrementBucket(deltaCounts, bucket);
    }

    if (!state.completed && row.bpm >= state.goal_bpm) {
      state.completed = true;
      incrementBucket(sessionsToCompleteCounts, state.session_count);
      const days = Math.max(1, diffDaysUtc(state.first_date!, row.date) + 1);
      incrementBucket(daysToCompleteCounts, days);
    }

    state.prev_bpm = row.bpm;
    lickState.set(row.lick_id, state);
  }

  return {
    session_deltas: toSortedBins(deltaCounts),
    sessions_to_complete: toSortedBins(sessionsToCompleteCounts),
    days_to_complete: toSortedBins(daysToCompleteCounts),
  };
}

export function formatLocalDate(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export function normalizeLocalDate(value: string | null | undefined): string {
  if (!value) {
    return formatLocalDate();
  }
  const trimmed = value.trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) {
    throw new Error("X-Local-Date must be YYYY-MM-DD");
  }
  return trimmed;
}
